"""Add Inventory and Sales tables

Revision ID: c21b242f6c7d
Revises: dcb68c476e3a
Create Date: 2025-05-16 18:20:21.620373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21b242f6c7d'
down_revision = 'dcb68c476e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('sales_amount', sa.Float(), nullable=False),
    sa.Column('sales_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
